name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - uat

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build React application
        run: npm run build

      - name: Deploy to S3 - UAT
        if: github.ref == 'refs/heads/uat'
        run: aws s3 sync build/ s3://your-uat-s3-bucket

      - name: Deploy to S3 - Main
        if: github.ref == 'refs/heads/main'
        run: aws s3 sync build/ s3://your-main-s3-bucket
