export const PLAYLIST = [
    { id: 1, playlist: "Ambient" },
    { id: 2, playlist: "Electronic" },
    { id: 3, playlist: "Blues" },
    { id: 4, playlist: "Acoustic" },
    { id: 5, playlist: "Children" },
    { id: 6, playlist: "Ambients" },
    { id: 7, playlist: "Fantasy" },
    { id: 8, playlist: "Funks" },
    { id: 9, playlist: "Lounge" },
    { id: 10, playlist: "Classical" },
    { id: 11, playlist: "song-writer" },
    { id: 12, playlist: "Pop" },
    { id: 13, playlist: "Classicals" },
    { id: 14, playlist: "Regge" },
    { id: 15, playlist: "Holiday" },
    { id: 16, playlist: "Cinematic" },
    { id: 17, playlist: "Folk" },
    { id: 18, playlist: "Retro" },
    { id: 19, playlist: "Jazz" },
    { id: 20, playlist: "Funk" },
    { id: 21, playlist: "Soul" },
    { id: 22, playlist: "R&B" },
    { id: 23, playlist: "Lounges" },
]